name: my_pml
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.1
  appwrite: ^13.0.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/logo-nginepin.png

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/images/logo-nginepin.png # Path to your splash image
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
